Now absolute paths are not used for commands

diff --git a/base/contents/verify_install_node b/base/contents/verify_install_node
--- a/base/contents/verify_install_node
+++ b/base/contents/verify_install_node
@@ -42,12 +42,6 @@ if [ $# != 5 -o "${1}" == "help" ]; then
   exit 1
 fi
 
-# Use absolute paths for safety
-CURL='/usr/bin/curl'
-MKDIR='/bin/mkdir'
-RM='/bin/rm'
-TAR='/bin/tar'
-
 # The URL of the location from which the specified Node.js file
 # and checksum file can be downloaded
 base_url="${1}"
@@ -89,7 +83,7 @@ function warn {
 
 # Used to cleanup any temporary directories
 function cleanUp {
-  ${RM} -Rf "${tmp_dir}"
+  rm -Rf "${tmp_dir}"
 }
 
 # Used to cleanup any temporary directories and immediately exit this
@@ -152,13 +146,13 @@ function handleFailedVerification {
 
 # Make sure we are in the correct place in the fs and it is pristine
 cleanUp
-${MKDIR} -p "${tmp_dir}"
+mkdir -p "${tmp_dir}"
 cd "${tmp_dir}"
 
-# Use the --fail option so that a non-zero exit code is produced if a 
+# Use the --fail option so that a non-zero exit code is produced if a
 # 404 error is encountered
-${CURL} --fail -O ${base_url}/${node_filename} || exitAsFailure
-${CURL} --fail -O ${base_url}/${checksum_file} || handleFailedChecksumDownload
+curl --fail -O ${base_url}/${node_filename} || exitAsFailure
+curl --fail -O ${base_url}/${checksum_file} || handleFailedChecksumDownload
 
 # The verify node script has a non-zero exit code on failure
 /opt/google_appengine/runtime/verify_node ${node_filename} ${checksum_file} \
@@ -168,11 +162,11 @@ ${CURL} --fail -O ${base_url}/${checksum_file} || handleFailedChecksumDownload
 # First, remove the installation directory to prepare for a fresh install
 # Note: The -f option is used with rm so that rm will still succeed if
 #       the installation directory doesn't exist.
-(${RM} -Rf "${install_dir}") || exitAsFailure
-(${MKDIR} -p "${install_dir}") || exitAsFailure
+(rm -Rf "${install_dir}") || exitAsFailure
+(mkdir -p "${install_dir}") || exitAsFailure
 
 # Do the actual installation
-(${TAR} xvzf "${tmp_dir}/${node_filename}" -C "${install_dir}" --strip-components=1) \
+(tar xvzf "${tmp_dir}/${node_filename}" -C "${install_dir}" --strip-components=1) \
   || exitAsFailure
 
 # Remove any temporary directories
