veryify_install_node is always used to install Node
`Dockerfile` and `install_node` both delegate work to
`install_verify_node` to do the actual installation of Node.

diff --git a/base/verify_install_node b/base/verify_install_node
--- a/base/verify_install_node
+++ b/base/verify_install_node
@@ -4,30 +4,45 @@
 set -e
 
 # Bail with a help message if the arguments look wrong
-if [ $# != 2 -o "${1}" == "help" ]; then
-  echo "Usage: ${0} <node version number> <install dir>"
+if [ $# != 4 -o "${1}" == "help" ]; then
+  echo "Usage: ${0} <base url> <node version number> <checksum filename> <install dir>"
   echo ""
   echo "Verifies and installs the specified version of Node.js to the"
   echo "specified directory where the version number is expected to be"
   echo "of the form 'v#.#.#'."
   echo ""
-  echo "An exit code of 0 indicates success and a non-zero exit code "
-  echo "indicates failure."
+  echo "The Node.js binary with the specified version and the checksum"
+  echo "file with the specified name will be downloaded from the specified"
+  echo "base url."
+  echo ""
+  echo "Note:  The installation directory will be deleted completely"
+  echo "       before the installation takes place."
+  echo ""
+  echo "An exit code of 0 indicates success and a non-zero exit code"
+  echo "indicates failure.  A failure will occur if the Node.js binary"
+  echo "file could not be downloaded, the checksum file could not be"
+  echo "downloaded, the installation directory could not be created "
+  echo "(if it doesn't already exist), or the verification of the "
+  echo "Node.js binary fails."
   exit 1
 fi
 
+# The URL of the location from which the specified Node.js file 
+# and checksum file can be downloaded
+base_url="${1}"
 
 # The node version to install expected to be of the form 'v#.#.#'
-node_version="${1}"
+node_version="${2}"
+
+# The name of the checksum file found in ${base_url} that is used to
+# verify the Node.js binary
+checksum_file="${3}"
 
 # The location where the Node will be installed
-install_dir="${2}"
+install_dir="${4}"
 
 # The name of the Node.js binary to install
 node_filename="node-${node_version}-linux-x64.tar.gz"
-
-# The name of the checksum file used to verify the Node.js binary
-checksum_file='SHASUMS256.txt.asc'
 
 # The temporary location where the downloaded files are stored while being
 # verified.  The script will ensure that this directory is removed before 
@@ -46,18 +61,19 @@ cd "${tmp_dir}"
 
 # wget is used over curl so that a non-zero exit code is produced if a 
 # 404 error is encountered
-wget https://nodejs.org/dist/${node_version}/${node_filename} \
-  || (cleanUp; exit 1)
-wget https://nodejs.org/dist/${node_version}/${checksum_file} \
-  || (cleanUp; exit 1)
+wget ${base_url}/${node_filename} || (cleanUp; exit 1)
+wget ${base_url}/${checksum_file} || (cleanUp; exit 1)
 
 # The verify node script has a non-zero exit code on failure
 /opt/nodejs/verify_node ${node_filename} ${checksum_file} \
   || (cleanUp; exit 1)
 
 # If the verification is successful, proceed to install Node
-(mkdir "${install_dir}" ) \
-  || (cleanUp; exit 1)
+# First, remove the installation directory to prepare for a fresh install
+# Note: The -f option is used with rm so that rm will still succeed if
+#       the installation directory doesn't exist.
+(rm -Rf "${install_dir}") || (cleanUp; exit 1)
+(mkdir -p "${install_dir}") || (cleanUp; exit 1)
 
 (tar xvzf "${tmp_dir}/${node_filename}" -C "${install_dir}" --strip-components=1) \
   || (cleanUp; exit 1)
